// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ssa
Rcpp::DataFrame ssa(SEXP network_ptr, arma::vec y, arma::vec tspan);
RcppExport SEXP _reactor_ssa(SEXP network_ptrSEXP, SEXP ySEXP, SEXP tspanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type network_ptr(network_ptrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tspan(tspanSEXP);
    rcpp_result_gen = Rcpp::wrap(ssa(network_ptr, y, tspan));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reactor_ssa", (DL_FUNC) &_reactor_ssa, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_reactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
