# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

issa_cpp <- function(rnet_xptr, D, volume_xptr, T, length_out = 100L, all_out = FALSE, verbose = TRUE, k_vec = NULL) {
    .Call(`_rendr_issa_cpp`, rnet_xptr, D, volume_xptr, T, length_out, all_out, verbose, k_vec)
}

nsm_cpp <- function(rnet_xptr, D, volume_xptr, T, length_out = 100L, all_out = FALSE, verbose = TRUE, k_vec = NULL) {
    .Call(`_rendr_nsm_cpp`, rnet_xptr, D, volume_xptr, T, length_out, all_out, verbose, k_vec)
}

nsm_cpp_pest <- function(rnet_xptr, D, volume_xptr, T, trajectories = 1L, k_vec = NULL) {
    .Call(`_rendr_nsm_cpp_pest`, rnet_xptr, D, volume_xptr, T, trajectories, k_vec)
}

ssa_cpp <- function(rnet_xptr, y, T, length_out = 100L, all_out = FALSE, k_vec = NULL, seed_val = NULL) {
    .Call(`_rendr_ssa_cpp`, rnet_xptr, y, T, length_out, all_out, k_vec, seed_val)
}

ssa_cpp_pest <- function(rnet_xptr, y, T, trajectories = 1L, k_vec = NULL) {
    .Call(`_rendr_ssa_cpp_pest`, rnet_xptr, y, T, trajectories, k_vec)
}

ssa_cpp_trajest <- function(rnet_xptr, y, T, trajectories = 1L, length_out = 100L, k_vec = NULL) {
    .Call(`_rendr_ssa_cpp_trajest`, rnet_xptr, y, T, trajectories, length_out, k_vec)
}

ssa_cpp_count <- function(rnet_xptr, y, T, k_vec = NULL) {
    .Call(`_rendr_ssa_cpp_count`, rnet_xptr, y, T, k_vec)
}

prop_px <- function(rnet_xptr, x, pi, xi) {
    .Call(`_rendr_prop_px`, rnet_xptr, x, pi, xi)
}

tauleap_cpp <- function(rnet_xptr, y, T, hots, reverse, length_out = 100L, all_out = FALSE, k_vec = NULL, verbose = FALSE) {
    .Call(`_rendr_tauleap_cpp`, rnet_xptr, y, T, hots, reverse, length_out, all_out, k_vec, verbose)
}

tauleap_implicit_cpp <- function(rnet_xptr, y, T, length_out = 100L, all_out = FALSE, k_vec = NULL) {
    .Call(`_rendr_tauleap_implicit_cpp`, rnet_xptr, y, T, length_out, all_out, k_vec)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rendr_RcppExport_registerCCallable', PACKAGE = 'rendr')
})
