# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nsm_cpp <- function(network_ptr, diffusions, y_volume_ptr, h, tspan) {
    .Call(`_reactor_nsm_cpp`, network_ptr, diffusions, y_volume_ptr, h, tspan)
}

ssa_cpp <- function(network_ptr, y, tspan) {
    .Call(`_reactor_ssa_cpp`, network_ptr, y, tspan)
}

