# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

issa_cpp <- function(rnet_xptr, D, volume_xptr, T, length_out = 100L, all_out = FALSE, verbose = TRUE) {
    .Call(`_rendr_issa_cpp`, rnet_xptr, D, volume_xptr, T, length_out, all_out, verbose)
}

nsm_cpp <- function(rnet_xptr, D, volume_xptr, T, length_out = 100L, all_out = FALSE, verbose = TRUE) {
    .Call(`_rendr_nsm_cpp`, rnet_xptr, D, volume_xptr, T, length_out, all_out, verbose)
}

ssa_cpp <- function(rnet_xptr, y, T, length_out = 100L, all_out = FALSE, k_vec = NULL) {
    .Call(`_rendr_ssa_cpp`, rnet_xptr, y, T, length_out, all_out, k_vec)
}

ssa_cpp_pest <- function(rnet_xptr, y, T, trajectories, k_vec = NULL) {
    .Call(`_rendr_ssa_cpp_pest`, rnet_xptr, y, T, trajectories, k_vec)
}

tauleap_cpp <- function(rnet_xptr, y, T, hors, hots, reverse, length_out = 100L, all_out = FALSE, k_vec = NULL) {
    .Call(`_rendr_tauleap_cpp`, rnet_xptr, y, T, hors, hots, reverse, length_out, all_out, k_vec)
}

tauleap_implicit_cpp <- function(rnet_xptr, y, T, length_out = 100L, all_out = FALSE, k_vec = NULL) {
    .Call(`_rendr_tauleap_implicit_cpp`, rnet_xptr, y, T, length_out, all_out, k_vec)
}

